apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp2-clearing-manager-ui
  namespace: test-project
  labels:
    app: wp2-clearing-manager-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp2-clearing-manager-ui

  template:
    metadata:
      labels:
        app: wp2-clearing-manager-ui
    spec:

      containers:

        - name: wp2-clearing-manager-ui
          image: acrtestproject.azurecr.io/clearing-manager-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wp2-clearing-manager-ui-service
  namespace: test-project
  labels:
    app: wp2-clearing-manager-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: wp2-clearing-manager-ui
  type: LoadBalancer